---

- hosts: localhost
  gather_facts: False
  tasks:

    - name: index_cookbook_entities
      shell: ruby {{ item }}
      args:
        chdir: "{{ dataspectsSystem_control_folder_on_host }}/control_scripts"
      with_items:
        - index_cookbook_entities.rb
      tags:
        - index_cookbook_entities
