---

- hosts: localhost
  gather_facts: False
  tasks:

    - name: Clone dataspectsSystemCoreOntology, dataspects_lib, dataspects_api
      git:
        repo: "git@github.com:dataspects/{{ item }}.git"
        dest: "{{ dataspectsSystem_path_on_host }}/workspace/{{ item }}"
      with_items:
        - dataspects_lib
        - dataspects_api
        - dataspectsSystemCoreOntology
      tags:
        - inject_dataspectsSystemCoreOntology

    - name: inject_dataspectsSystemCoreOntology_into_mediawiki.rb
      template:
        src: ../scripts/inject_dataspectsSystemCoreOntology_into_mediawiki.rb
        dest: "{{ dataspectsSystem_path_on_host }}/workspace/inject_dataspectsSystemCoreOntology_into_mediawiki.rb"
        mode: 0777
      tags:
        - inject_dataspectsSystemCoreOntology

    # [[IsOperationType::RunDockerContainer]]
    - name: Inject dataspectsSystemCoreOntology into mediawiki
      shell: docker run \
              --volume {{ dataspectsSystem_path_on_host }}/workspace/:/usr/src/workspace \
              --workdir /usr/src/workspace/dataspects_lib \
              --network dataspectsstandardsystem_default \
              --ip 172.21.0.99 \
              --rm \
                dataspects/dataspects:{{ dataspects_version }} \
                  bundle exec bin/dataspects \
                    --profile /usr/src/workspace/standard_system_profiles.yml \
                      manage /usr/src/workspace/inject_dataspectsSystemCoreOntology_into_mediawiki.rb
      ignore_errors: yes
      become: true
      tags:
        - inject_dataspectsSystemCoreOntology
