---

- hosts: localhost
  gather_facts: False
  tasks:

    ############################################################################
    - name: Register {{ dataspectsSystem_path_on_host | basename | lower }}_mediawiki_root path on host
      shell: docker volume inspect {{ dataspectsSystem_path_on_host | basename | lower }}_mediawiki_root
      register: volume_profile
      tags:
        - install_mediawiki
    - set_fact: mountpoint={{ dict(volume_profile.stdout | from_json | json_query('[].[Name,Mountpoint]')) }}
      tags:
        - install_mediawiki
    ############################################################################

    - name: Copy mediawiki core to volume
      synchronize:
        src: ../mediawiki/
        dest: "{{ mountpoint.items()[0][1] }}"
      become: true
      tags:
        - install_mediawiki

    - name: Checkout required mediawiki version
      shell: "git checkout {{ mediawiki_version }}"
      args:
        chdir: "{{ mountpoint.items()[0][1] }}"
      become: true
      tags:
        - install_mediawiki

    - name: Install extensions and skins
      shell: "git submodule update --init --recursive"
      args:
        chdir: "{{ mountpoint.items()[0][1] }}"
      become: true
      tags:
        - install_mediawiki

    # [[IsOperationType::FileSystemOperation]]
    - name: Set permissions on mediawiki root
      file:
        path: "{{ mountpoint.items()[0][1] }}"
        owner: www-data
        recurse: yes
      become: true
      tags:
        - install_mediawiki

    - name: Place composer install script
      template:
        src: ../ansible_templates/install_composer.sh
        dest: "{{ mountpoint.items()[0][1] }}/install_composer.sh"
        mode: 0777
      become: true
      tags:
        - install_mediawiki

    - name: Install composer locally
      shell: docker exec {{ dataspectsSystem_path_on_host | basename | lower }}_web_1 bash -c "cd /var/www/html/w && ./install_composer.sh"
      tags:
        - install_mediawiki

    # [[IsOperationType::VendorPackageOperation]]
    - name: Run composer inside container
      shell: docker exec {{ dataspectsSystem_path_on_host | basename | lower }}_web_1 bash -c "cd /var/www/html/w && php composer.phar install"
      tags:
        - install_mediawiki

    # [[IsOperationType::FileSystemOperation]]
    - name: Place mediawiki install script
      template:
        src: ../ansible_templates/install_mediawiki.sh.j2
        dest: "{{ mountpoint.items()[0][1] }}/install.sh"
        mode: 0777
      become: true
      tags:
        - install_mediawiki

    # [[IsOperationType::VendorPackageOperation]]
    - name: Install mediawiki inside container
      shell: "docker exec {{ dataspectsSystem_path_on_host | basename | lower }}_web_1 bash -c 'cd /var/www/html/w && ./install.sh'"
      tags:
        - install_mediawiki

    - name: Configure LocalSettings.php
      lineinfile:
        path: "{{ mountpoint.items()[0][1] }}/LocalSettings.php"
        line: "{{ item }}"
        # insertafter: $wgScriptPath = '/w';
      with_items:
        - $wgArticlePath = '/wiki/$1';
        - $wgFileExtensions[] = 'pdf';
      become: true
      tags:
        - install_mediawiki

    # [[IsOperationType::VendorPackageOperation]]
    - name: Change admin user password
      shell: docker exec {{ dataspectsSystem_path_on_host | basename | lower }}_web_1 bash
               -c "cd /var/www/html/w/maintenance &&
                   php changePassword.php --user='admin' --password='{{ mediawiki_admin_user_password }}'"
      become: true
      tags:
        - install_mediawiki
