---

- hosts: localhost
  gather_facts: False
  tasks:

    - name: Copy mediawiki core to volume
      synchronize:
        src: ../mediawiki/
        dest: "/var/lib/docker/volumes/dataspectsstandardsystem_mediawiki_root/_data"
      become: true
      tags:
        - install_mediawiki

    - name: Checkout required mediawiki version
      shell: "git checkout {{ mediawiki_version }}"
      args:
        chdir: "/var/lib/docker/volumes/dataspectsstandardsystem_mediawiki_root/_data"
      become: true
      tags:
        - install_mediawiki

    - name: Install extensions and skins
      shell: "git submodule update --init --recursive"
      args:
        chdir: "/var/lib/docker/volumes/dataspectsstandardsystem_mediawiki_root/_data"
      become: true
      tags:
        - install_mediawiki

    # # [[IsOperationType::FileSystemOperation]]
    # - name: Set permissions on mediawiki root
    #   file:
    #     path: "/var/lib/docker/volumes/dataspectsstandardsystem_mediawiki_root/_data"
    #     owner: www-data
    #     recurse: yes
    #   become: true
    #   tags:
    #     - install_mediawiki
    #

    - name: Place composer install script
      template:
        src: ../ansible_templates/install_composer.sh
        dest: "/var/lib/docker/volumes/dataspectsstandardsystem_mediawiki_root/_data/install_composer.sh"
        mode: 0777
      become: true
      tags:
        - install_mediawiki

    - name: Install composer locally
      shell: docker exec dataspectsstandardsystem_php-fpm_1 bash -c "cd /var/www/html/w && ./install_composer.sh"
      tags:
        - install_mediawiki

    # [[IsOperationType::VendorPackageOperation]]
    - name: Run composer inside container
      shell: docker exec dataspectsstandardsystem_php-fpm_1 bash -c "cd /var/www/html/w && php composer.phar install"
      tags:
        - install_mediawiki

    # [[IsOperationType::FileSystemOperation]]
    - name: Place mediawiki install script
      template:
        src: ../ansible_templates/install_mediawiki.sh.j2
        dest: "/var/lib/docker/volumes/dataspectsstandardsystem_mediawiki_root/_data/install.sh"
        mode: 0777
      become: true
      tags:
        - install_mediawiki

    # [[IsOperationType::VendorPackageOperation]]
    - name: Install mediawiki inside container
      shell: "docker exec dataspectsstandardsystem_php-fpm_1 bash -c 'cd /var/www/html/w && ./install.sh'"
      tags:
        - install_mediawiki

    # [[IsOperationType::VendorPackageOperation]]
    - name: Change admin user password
      shell: docker exec dataspectsstandardsystem_php-fpm_1 bash
               -c "cd /var/www/html/w/maintenance &&
                   php changePassword.php --user='admin' --password='{{ mediawiki_admin_user_password }}'"
      become: true
      tags:
        - install_mediawiki
