---

- hosts: localhost
  gather_facts: False
  tasks:

    ############################################################################
    - name: Register {{ dataspectsSystem_path_on_host | basename | lower }}_mediawiki_root path on host
      shell: docker volume inspect {{ dataspectsSystem_path_on_host | basename | lower }}_mediawiki_root
      register: volume_profile
      tags:
        - install_bluespice_pro
        - temp
    - set_fact: mountpoint_mw={{ dict(volume_profile.stdout | from_json | json_query('[].[Name,Mountpoint]')) }}
      tags:
        - install_bluespice_pro
        - temp
    ############################################################################

    - name: Copy BlueSpice Pro core to volume
      synchronize:
        src: ../bluespice/
        dest: "{{ mountpoint_mw.items()[0][1] }}"
      become: true
      tags:
        - install_bluespice_pro

    # [[IsOperationType::FileSystemOperation]]
    - name: Place mediawiki install script
      template:
        src: ../ansible_templates/install_mediawiki.sh.j2
        dest: "{{ mountpoint_mw.items()[0][1] }}/install.sh"
        mode: 0777
      become: true
      tags:
        - install_bluespice_pro

    # [[IsOperationType::FileSystemOperation]]
    - name: Set permissions on mediawiki root
      file:
        path: "{{ mountpoint_mw.items()[0][1] }}"
        owner: www-data
        recurse: yes
      become: true
      tags:
        - install_bluespice_pro
        - temp

    # [[IsOperationType::VendorPackageOperation]]
    - name: Install BlueSpice inside container
      shell: "docker exec {{ dataspectsSystem_path_on_host | basename | lower }}_web_1 bash -c 'cd /var/www/html/w && ./install.sh'"
      tags:
        - install_bluespice_pro

    - name: Run maintenance/update.php
      shell: docker exec {{ dataspectsSystem_path_on_host | basename | lower }}_web_1 bash -c "cd /var/www/html/w && php maintenance/update.php"
      become: true
      tags:
        - install_bluespice_pro

    - name: Change admin user password
      shell: docker exec {{ dataspectsSystem_path_on_host | basename | lower }}_web_1 bash
               -c "cd /var/www/html/w/maintenance &&
                   php changePassword.php --user='admin' --password='{{ mediawiki_admin_user_password }}'"
      become: true
      tags:
        - install_bluespice_pro

    - name: Register VisualEditor in LocalSettings.php
      lineinfile:
        path: "{{ mountpoint_mw.items()[0][1] }}/LocalSettings.php"
        line: "{{ item }}"
      with_items:
        - "wfLoadExtension( 'VisualEditor' );"
        - "$wgDefaultUserOptions['visualeditor-enable'] = 1;"
        - "$wgHiddenPrefs[] = 'visualeditor-enable';"
        - "$wgVirtualRestConfig['modules']['parsoid'] = array('url' => 'http://parsoid:8000');"
      become: true
      tags:
        - install_bluespice_pro

    - name: Configure dockerized Elasticsearch
      lineinfile:
        path: "{{ mountpoint_mw.items()[0][1] }}/LocalSettings.php"
        line: "{{ item }}"
      with_items:
        - "$bsgOverrideESBackendHost = 'http://elasticsearch:9200';"
        # Missing tomcat override!
      become: true
      tags:
        - install_bluespice_pro

    # extensions/BlueSpiceExtendedSearch/docs/README.md
    # php extensions/BlueSpiceExtendedSearch/maintenance/rebuildIndex.php && php maintenance/runJobs.php

    ############################################################################
    # Webservices
    - name: Register {{ dataspectsSystem_path_on_host | basename | lower }}_tomcat_root path on host
      shell: docker volume inspect {{ dataspectsSystem_path_on_host | basename | lower }}_tomcat_root
      register: volume_profile
      tags:
        - install_bluespice_pro
        - temp
    - set_fact: mountpoint_tc={{ dict(volume_profile.stdout | from_json | json_query('[].[Name,Mountpoint]')) }}
      tags:
        - install_bluespice_pro
        - temp

    - name: Copy BShtml2PDF.war
      synchronize:
        src: "{{ mountpoint_mw.items()[0][1] }}/extensions/{{ item.path }}/webservices/{{ item.name }}"
        dest: "{{ mountpoint_tc.items()[0][1] }}/{{ item.name }}"
      with_items:
        - { path: 'BlueSpiceUEModulePDF', name: 'BShtml2PDF.war' }
        - { path: 'BlueSpiceVisualDiff', name: 'BShtmlDiff.war' }
        - { path: 'BlueSpiceLatexRenderer', name: 'BSLaTeX2PNG.war' }
      become: true
      tags:
        - install_bluespice_pro
        - temp
