---

- hosts: localhost
  gather_facts: False
  tasks:

    ############################################################################
    - name: Register {{ dataspectsSystem_path_on_host | basename | lower }}_mediawiki_root path on host
      shell: docker volume inspect {{ dataspectsSystem_path_on_host | basename | lower }}_mediawiki_root
      register: volume_profile
      tags:
        - install_bluespice_pro
    - set_fact: mountpoint={{ dict(volume_profile.stdout | from_json | json_query('[].[Name,Mountpoint]')) }}
      tags:
        - install_bluespice_pro
    ############################################################################

    - name: Copy BlueSpice Pro core to volume
      synchronize:
        src: ../bluespice/
        dest: "{{ mountpoint.items()[0][1] }}"
      become: true
      tags:
        - install_bluespice_pro

    # [[IsOperationType::FileSystemOperation]]
    - name: Place mediawiki install script
      template:
        src: ../ansible_templates/install_mediawiki.sh.j2
        dest: "{{ mountpoint.items()[0][1] }}/install.sh"
        mode: 0777
      become: true
      tags:
        - install_bluespice_pro

    # [[IsOperationType::VendorPackageOperation]]
    - name: Install BlueSpice inside container
      shell: "docker exec {{ dataspectsSystem_path_on_host | basename | lower }}_web_1 bash -c 'cd /var/www/html/w && ./install.sh'"
      tags:
        - install_bluespice_pro

    - name: Run maintenance/update.php
      shell: docker exec {{ dataspectsSystem_path_on_host | basename | lower }}_web_1 bash -c "cd /var/www/html/w && php maintenance/update.php"
      become: true
      tags:
        - install_bluespice_pro

    - name: Change admin user password
      shell: docker exec {{ dataspectsSystem_path_on_host | basename | lower }}_web_1 bash
               -c "cd /var/www/html/w/maintenance &&
                   php changePassword.php --user='admin' --password='{{ mediawiki_admin_user_password }}'"
      become: true
      tags:
        - install_bluespice_pro

    - name: Register VisualEditor in LocalSettings.php
      lineinfile:
        path: "{{ mountpoint.items()[0][1] }}/LocalSettings.php"
        line: "{{ item }}"
      with_items:
        - "wfLoadExtension( 'VisualEditor' );"
        - "$wgDefaultUserOptions['visualeditor-enable'] = 1;"
        - "$wgHiddenPrefs[] = 'visualeditor-enable';"
        - "$wgVirtualRestConfig['modules']['parsoid'] = array('url' => 'http://parsoid:8000');"
      become: true
      tags:
        - install_bluespice_pro


# ~/mediawiki/w/extensions/BlueSpiceExtendedSearch$ sudo vi extension.json
# vagrant@dataspects-full-on-single-machine:~/mediawiki/w/extensions/BlueSpiceExtendedSearch/docs$ vi README.md

# sysctl -w vm.max_map_count=262144 on VM????
