---

- hosts: localhost
  gather_facts: False
  tasks:

    - name: Copy control config files
      copy:
        src: ../ansible_templates/provisioning/elasticsearch
        dest: "{{ dataspectsSystem_control_folder_on_host }}/provisioning"
      tags:
        - provision_and_index

    - name: Copy control files
      template:
        src: "../ansible_templates/provisioning/{{ item }}.j2"
        dest: "{{ dataspectsSystem_control_folder_on_host }}/provisioning/{{ item }}"
        mode: 0777
      with_items:
        - execute_all.rb
        - inject_core_ontology.rb
        - inject_cookbook_ontology.rb
        - inject_cookbook_entities.rb
        - index_cookbook_entities.rb
      tags:
        - provision_and_index

    - name: Execute all control files
      shell: ruby execute_all.rb
      args:
        chdir: "{{ dataspectsSystem_control_folder_on_host }}/provisioning"
      tags:
        - provision_and_index
