---

- hosts: localhost
  gather_facts: False
  tasks:

    - name: Run docker-compose
      shell: docker-compose \
               --file {{ dataspectsSystem_path_on_host }}/docker-compose.yml \
                 up \
                   --detach
      tags:
        - run_docker_compose
