---

- hosts: localhost
  gather_facts: False
  tasks:

    - name: Run docker-compose
      command: docker-compose \
                 --file {{ dataspectsSystem_path_on_host }}/docker-compose.yml \
                   up
                     --detach
      become: true
      tags:
        - run_docker_compose
